name: Flutter CI
on: push
jobs:
  formating:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get deps
        run: flutter pub get

      - name: Format checking
        run: dart format --output=none --set-exit-if-changed .

  lint:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get deps
        run: flutter pub get

      - name: Lint check
        run: flutter analyze

  build-apk:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get deps
        run: flutter pub get

      - name: Build APK
        run: flutter build apk
